[project]

site_name = "Introdução a Modelagem paramétrica"
site_url = "https://255ribeiro.github.io/introducao_a_modelagem_parametrica/"

repo_url = "https://github.com/255ribeiro/introducao_a_modelagem_parametrica/"
repo_name = "255ribeiro/introducao_a_modelagem_parametrica/"

site_description = "Anotações de aula para a disciplina de introdução à topografia"
site_author = "Fernando Ferraz Ribeiro"

copyright = """
Copyright &copy; 2026 The authors
"""

extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js"
#     "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js",  # 1st - the library
#     "javascripts/download_zip_folder.js"                                 # 2nd - your code that uses it
]




nav = [
{"Home" = "index.md" },
{"Pré-requisitos" = [{"Rhinoceros 3D" = "https://255ribeiro.github.io/intro_rhino/"},
{"Configurações de atalhos" = "https://255ribeiro.github.io/intro_rhino/atalhosRhino/atalhosRhino.html"}
]},
{"Sobre o Grashopper" = "grass_about/grass_about.md"},
{"Interface" = [
{"Janela do Grasshopper" = "gh_interface/gh_inter.md"},
{"Sliders" = "Slider/Slider_config.md"},
{"Panels" = "Panels/Painel_config.MD"},

]},

{"Manipulação de listas" = "gh_list_intro/gh_list_basics.md"},
{"Vetores e Planos" = "gh_vect_plane/vect_plane_basics.md"},

{"Exemplos" = "gh_exemplos/gh-exemplos.md"},
{"Links úteis" = "links_refs/links_refs.md"}
]

[project.theme]
variant = "classic"
language = "pt-BR"


features = [
    "announce.dismiss",                  # allows users to dismiss the announcement bar
    # "content.action.view",             # adds a button to view the page source
    # "content.action.edit",             # adds a button to edit the page in the repo
    "content.code.annotate",             # enables annotations inside code blocks
    "content.code.copy",                 # adds a copy button to code blocks
    "content.code.select",               # adds a line range selection button to code blocks
    "content.footnote.tooltips",         # renders footnotes as inline tooltips
    "content.tabs.link",                 # syncs all content tabs with the same label
    "content.tooltips",                  # enables tooltips on links
    # "header.autohide",                 # hides header when scrolling down
    # "navigation.expand",               # expands all nav sections by default
    # "navigation.footer",               # adds prev/next page links in footer
    # "navigation.indexes",              # attaches index.md to section headers
    "navigation.instant",                # enables instant navigation via XHR
    "navigation.instant.prefetch",       # prefetches pages on link hover
    "navigation.instant.progress",       # shows progress bar on slow connections
    "navigation.path",                   # shows breadcrumb above page title
    # "navigation.prune",                # only renders visible nav items (reduces size)
    # "navigation.sections",             # renders top-level sections as flat groups
    # "navigation.tabs",                 # renders top-level sections as header tabs
    # "navigation.tabs.sticky",          # keeps tabs visible while scrolling
    "navigation.top",                    # shows back-to-top button
    "navigation.tracking",               # updates URL with active anchor
    "search.highlight",                  # highlights search terms after following result
    "search.share",                      # adds a share button to search results
    "search.suggest",                    # shows search suggestions while typing
    "toc.follow",                        # auto-scrolls TOC to active anchor
    # "toc.integrate",
    "content.footnote.tooltips"                  # moves TOC into the left navigation sidebar
]

[project.theme.icon]
logo = "fontawesome/solid/globe"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "lime"
accent = "yellow"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"


# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "lime"
accent = "yellow"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions]
attr_list = {}
md_in_html = {}
pymdownx.blocks.caption = {}

[project.markdown_extensions.footnotes]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.toc]
toc_depth = 1



[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/255ribeiro"
name = "GitHub"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/fernando-ferraz-ribeiro-b49a7bb0/"
name = "LinkedIn"

[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/@ferrax"
name = "youtube"

[[project.extra.social]]
icon = "fontawesome/solid/envelope"
link = "mailto:ffribeiro@gmail.com"
name = "Email"